// Code generated by goctl. DO NOT EDIT.
export interface ErrMsg {
	ret?: number
	_errno?: number
	_errstr?: string
	_param?: any
}
export interface PageReq extends ErrMsg {
	page: number
	limit: number
}

export interface PageRsp extends ErrMsg {
	page: number
	limit: number
	total: number
}

export interface BasePage extends ErrMsg {
	page: number
	page_size: number
}

export interface NullReq extends ErrMsg {
	app_id: number
	user_id: number
	game_sum: string
	custome_sum: string
	app_version: string
	game_skin: string // 子游戏皮肤 字符串
	read_type: number // 0 团队 1自营 -1 全部
	aite_type: number // aite类型  4 新艾特
	aite_device: UserPayDevices // 版本信息
	device: UserPayDevices // 版本信息
	old_app_id: number // 老的
	lang: number // 語言
}

export interface NullRsp extends ErrMsg {
	data: string
}

export interface AppIDReq extends ErrMsg {
	app_id: number
}

export interface UserPayDevices extends ErrMsg {
	device_id?: string // 设备ID
	phone_model?: string // 手机型号 iphone6s
	phone_device_brand?: string // 设备厂商
	os_type?: number // 1 web 2 android 3 ios
	os_version?: string // 系统版本号
	app_version?: string // 客户端版本号
	ip: string // 客户端ip //服务端添加
}

export interface Tmps extends ErrMsg {
	stime: number
	etime: number
}

export interface GetPointRankInfo extends ErrMsg {
	point: number
	name?: string
	headimg?: string
	rank: number
	uid: number
	head: number
}

export interface PutServerChargeSetting extends ErrMsg {
	fee: number // n%
	min_point: number // n%
	max_point: number // n%
}

export interface PointLogTypeInfo extends ErrMsg {
	source: number
	name: string
}

export interface IndexReq extends ErrMsg {
	app_id: number
	appname: string
}

export interface IndexRsp extends ErrMsg {
	app_id?: number
	data: any
}

export interface SysConfigReq extends ErrMsg {
	app?: string
	app_id: number
	pack?: number
	uid: number
	token: string
	app_source?: string // app用的资源热更源代号
	edition?: string // 版本号
	old_app_id?: number
	//设备信息
	device?: ClientDevInfo
	hall_skin?: string // 大厅皮肤
	lang: number
	app_independent_tag?: string // app独立热更tag
}

export interface SysConfigRsp extends ErrMsg {
	app_id: number
	vip_list: Array<VipLevelConfig> // 层级配置
	vip_stage_list: Array<VipStageConfig> // 等级配置
	commi_config_list: Array<GAgentCommiConfig> // 佣金等级配置
	activity_cfg_list: Array<ActivityCfg> // 活动配置
	footer_cfg_md5: string // 页脚配置MD5
	banner_cfg_md5: string // 轮播图配置MD5
	game_type_list: Array<number> // 游戏配型
	my_activity_md5: string // 活动md5
	game_plat_list: Array<GgamePlatform> // 厂商列表
	pack_ext_code?: string
	activity_info_list: GetMyActivityListRsp // 活动信息
	reward_type_cfg: Array<RewardTypeConfig> // 奖励类型配置
	// 客户端更新提示
	update_notice?: NoticeInfo
	reg_type: number // 注册类型 0都开放  2账号注册 2手机号注册
	currency?: string // 货币类型
	point_ratio: number // APP配置的金币比例
	open_account_popup?: number
	data_hosts?: Array<string> // 客户端data域名数组
	debug?: number // 1 客户端开启debug
	official_url?: string // 官网地址
	server_id?: string // 服务器生成的唯一ID
	lang: Array<number> // 可用语言包
	login: number // 是否已登录 1 登录 0 未登录
	data: any // 数据 路由
	third_minpoint: number // 三方最低游戏金额
	desc_content_cfg_list: Array<DescContentCfg> // 模块提示文本跳转配置
}

export interface GAgentCommiConfig extends ErrMsg {
	app_id: number
	gclass: number
	commi_list: Array<GAgentCommiLevel>
	ignore_game_list: Array<number>
}

export interface GAgentCommiLevel extends ErrMsg {
	min_point: number
	max_point: number
	reward_id: string
	three_reward_id: string // 三级关联奖励id
	four_reward_id: string // 四级关联奖励id
	commi: number // 2级用户比例
	three_commi: number // 3级用户比例
	four_commi: number // 4级用户比例 // 2级用户比例
}

export interface NoticeInfo extends ErrMsg {
	appId: number // appid
	content?: string
	on_time?: number
	down_time?: number
	lang_repair_notify?: { [key: string]: string }
}

export interface RewardTypeConfig extends ErrMsg {
	reward_type: number // 配置类型
	title: { [key: string]: string } // 标题
}

export interface NodeConfigRsp extends ErrMsg {
	redis: any // redis配置
}

export interface CheckLoginReq extends ErrMsg {
	app_id: number
	uid: number
	token: string
}

export interface UserLoginReq extends ErrMsg {
	app_id: number
	email?: string // email
	phone?: string // 电话
	pwd: string // 密码
	code: string // 第三方code
	acode?: string // 区号
	remoteaddr?: string // 远程
	host?: string //
	os?: number // 操作系统
	rememberme?: number // 是否需要记住
	open_id?: string // 第三方OPENID
	nickname?: string //
	real_name?: string // 真实姓名
	head_img?: string // ---每次都要用
	source_type?: number // 来源 0// 1 openinstall 2 copy 3 cookie 4 get
	sub_type?: number // 第三方类型
	old_app_id?: number // 老appid
	reg_info?: string // 设备信息
	device?: ClientDevInfo // 设备信息
	lang: number // 语言
	invite_code?: number
	pack?: number
	// 新加登录注册参数
	first_map: string
	source_map: string
	is_token_login?: boolean
	token?: string
	source_param: string // 来源参数 tracker=aid23cid232&clickid=chh473bcch545
	receive_email: boolean // 是否接收推广邮件
}

export interface UserSelfCfg extends ErrMsg {
	head: number // 0默认 头像框
	pao: number // 0默认 捕鱼炮台
}

export interface VipPowerStruct extends ErrMsg {
	power: Array<number> // 有啥权力 1 可以设置相框 2可以设置炮台
	head: Array<number> // 可以设置那几个头像 1 2 3 4 5
	pao: Array<number> // 可以设置那几个炮台 1 2 3 4 5
}

export interface GetVerifyCodeReq extends ErrMsg {
	phone?: string
	code_type?: number
	acode?: string
	device?: ClientDevInfo // 设备信息
	verify_type: number // 0 sms 1 email
	email: string // email地址
	retry: number // 重试 0否 1是
	ostype: number // ostype  1 web
}

export interface VerifyCodeRsp extends ErrMsg {
	code: string // 验证码
}

export interface UserLoginRsp extends ErrMsg {
	uid: number
	token: string
	nickname: string
	real_name: string
	account?: string
	headimg: string
	point: number
	user_type: number // -----
	phone: string // 手机
	phone_bind: boolean // 手机是否绑定
	email: string // 邮箱
	email_bind: boolean // 邮箱是否绑定
	pack_no: number
	general: number
	pid: number
	bank_point: number // 银行金币
	open_id: string
	accesstoken: string
	routes: Array<TServer> // 返回游戏路由
	lroutes: Array<TServer> // 返回登录的路由
	t_url: string // 返回客户端测试的URL
	register_ip: string
	last_login_ip: string
	list_ip: string
	vip_coin: number // 当前等级
	vip_level: number // 当前等级
	next_coin: number // 离下一vip差多少
	self_cfg: UserSelfCfg
	vip_power?: VipPowerStruct
	server_id: string
	merge_point?: number
	merge_type: number
	cpf_account: string
	fname: string
	lname: string
	birth: string // 生日
	country: string // 国家
	state: string // 区
	city: string // 市
	street_address: string // 街道
	postal_code: string // 邮编
	all_put_code: number // 所需要的打码量
	ready_put_code: number // 已经的打码量
}

export type UserRegisterReq = ErrMsg

export interface HadPhoneRegReq extends ErrMsg {
	phone: string // 电话
	acode: string // 区号
}

export interface HadAccountRegRsp extends ErrMsg {
	had: boolean // true 已经存在
}

export interface HadEmailRegReq extends ErrMsg {
	email: string // email
}

export interface TokenInfoRsp extends ErrMsg {
	uid: number
	expiretime: number
	appid: number
	token: string
	is_free: boolean // 是否试玩
}

export interface NewEditPwdReq extends ErrMsg {
	pwd: string // 老密码
	new_pwd: string // 新密码
}

export interface SaveNoBindPhoneReq extends ErrMsg {
	acode?: string
	phone?: string
}

export interface SaveNoBindEmailReq extends ErrMsg {
	email?: string // email地址
}

export interface NewForgetCodeCheckReq extends ErrMsg {
	acode?: string
	phone?: string
	email?: string // email地址
	code: string // 验证码
}

export interface NewForgetPwdReq extends ErrMsg {
	key: string // 校验验证码时返回的data
	new_pwd: string // 新密码
}

export interface NewBindAccountReq extends ErrMsg {
	code: string
}

export interface UserOpenReq extends ErrMsg {
	app_id: number
	uid: number
}

export interface HeartBeatReq extends ErrMsg {
	app_id: number
	uids: Array<number>
}

export interface GetCustomeServiceRsp extends ErrMsg {
	data: CustomerServiceInfo
}

export interface CustomerServiceInfo extends ErrMsg {
	app_id: number // 盘口id
	key: number // 客服标识//10000  登录客服  10001 推广界面客服   10002 游戏大厅客服
	button?: string // 客服按钮描述
	status: number // 客服状态0不可用1可用
	update_time?: string // 更新时间
	url1: string // 外部链接1
	url2: string // 外部链接2
	url3: string // 外部链接3
	url4: string // 外部链接4
	lang_name_1: { [key: string]: string } // 名字1
	lang_name_2: { [key: string]: string } // 名字2
	lang_name_3: { [key: string]: string } // 名字3
	lang_name_4: { [key: string]: string } // 名字4
	type_1: number // 图标1
	type_2: number // 图标2
	type_3: number // 图标3
	type_4: number // 图标4
}

export interface GgamePlatformListRsp extends ErrMsg {
	list: Array<GgamePlatform>
}

export interface GgamePlatform extends ErrMsg {
	PlatId: number // 平台id
	name: string // 平台名字
	logo: string // logo
	power: number // 排序
	gclass: number // 分类
	status: number // 状态 0关闭 1开启
	enterGameMinPoint: number // 进入游戏最低金额 1=1*app汇率
}

export interface GAppFaqListRsp extends ErrMsg {
	list: Array<GAppFaqInfo>
}

export interface GAppFaqInfo extends ErrMsg {
	id: string
	app_id: number
	ctype: number // 类别
	topic: Array<string> // 关联主题
	status: number // 状态 0关闭 1开启
	ctime: number // 发布时间
	title: { [key: string]: string } // 标题
	content: { [key: string]: string } // 内容
}

export interface FooterCfgInfo extends ErrMsg {
	type: number // 类型
	status: number // 状态
	utime: number // 修改时间
	real_content: string
}

export interface GetFooterCfgRsp extends ErrMsg {
	list: Array<FooterCfgInfo>
	md5: string
}

export interface VipLevelConfig extends ErrMsg {
	id: number // id
	vip: number // vip等级
	vip_coin: number // vip积分
	stage_id: number // 层级id
	reward: RewardCfg // 奖励
}

export interface VipStageConfig extends ErrMsg {
	id: number // id  1-7
	ngame: number // 是否弹升级提示
	start_level: number // 起始等级
	end_level: number // 结束等级
	coin_rate: number // 积分比率
	logo: string // vip层级图标
	name: string // 层级名称  {"1":""} 后端转发
	image: string // vip层级图标
}

export interface DescContentCfg extends ErrMsg {
	id: number // 唯一id  规则模块  系统编号*10000 + id  10001 Vip图标 10002 Vip等级规则 10003 如何升级 10004 跳转按钮
	type: number // 类型 1 文本 2 图标url 3 跳转
	value: string // 内容
	utime: number // 更新时间
}

export interface GetVipCfgRsp extends ErrMsg {
	list: Array<VipLevelConfig> // 层级配置
	stage_list: Array<VipStageConfig> // 等级配置
}

export interface EnterGameReq extends ErrMsg {
	gid: number // 游戏ID
	ip: string
	lang: number // 语言
	externalURL: string
	demo: boolean // 是否是进试玩demo
	app_id: number
	os_type: number // 0未知 1 pc 2.安卓 app 3.ios APP 4.安卓web 5.ios web
}

export interface EnterGameRsp extends ErrMsg {
	url?: string // 登录该游戏的URL
	token?: string // 登录游戏的token
	method?: string // 请求方式
	betby_rsp?: any // BETBY返回的数据
	free_uid?: number // 试玩UID
	free_token?: string // 试玩token
}

export interface GetLotteryGameListRsp extends ErrMsg {
	game_list: Array<TAppLotteryGameNode>
	game_sum: string
}

export interface TAppLotteryGameNode extends ErrMsg {
	game_id?: number
	lotteryType: number // 彩票大类
	name?: string
	levels: Array<TAppGameLevel>
	status?: number
	top: number
	top2: number
	power?: number
	href?: string
	icon?: string
	gtype: number
	version?: string
	update_url?: string
	hit_update: GameHitUpdate
	pos: number
	ids: Array<number>
}

export interface TAppGameLevel extends ErrMsg {
	level?: string // level
	rule?: string // rule
	SceneName?: string
	PointLow: number // 上桌金币下限
	PointUpper?: number // 上桌金币上限
	PointRate?: number // 金币倍数,
	sub_cfg?: any // 添加的配置信息
	clieng_cfg?: any // 给客户端展示的配置
	max_lose: number // 最大赔付比例
	rate_tag: number // 场次等级
}

export interface GameHitUpdate extends ErrMsg {
	url: Array<string> // url
	version: string // 版本号
	param: string
	is_back: number
	new_url: Array<NewUpdateUrl>
}

export interface NewUpdateUrl extends ErrMsg {
	host?: string // 域名
	us_port?: number // 端口
	lo_type?: number // 链接类型 0 普通线路 1 字签证书 2云盾SDK 3智安盾
	url_type?: number // 固定值1  热更线路
	attr?: any // 附加字段
}

export interface BannerReq extends ErrMsg {
	app_id: number
}

export interface BannerRsp extends ErrMsg {
	list: Array<CPLunBoInfo>
	md5: string
}

export interface CPLunBoInfo extends ErrMsg {
	app_id: number
	id: string // id
	desc?: string // 描述
	jump_type: number // 0.不跳转, 1.跳转子游戏, 2.跳转游戏子目录, 3.跳转网页
	jump_url: string // 跳转内容
	img_url: string // 图片地址,key:语言, value:地址,语言: 0.默认, 1.英语, 2.越南语, 3.泰语, 4.繁体, 5.印尼语
	status: number // 状态, 1.启用, 2.禁用
	sort: number // 排序
	activity_id: number // 对应的活动id
}

export interface GetSoccerMatchListRsp extends ErrMsg {
	total: number
	list: Array<SoccerMatchInfo>
}

export interface SoccerMatchInfo extends ErrMsg {
	app_id: number
	static_id: string // 唯一ID
	league_name: string // 联赛名字
	league_logo?: string
	league_id: string // 联赛ID
	start_time: string // 比赛开始时间
	start_int: number // 比赛开始时间
	open_time: number // 下注开启时间
	stop_time: number // 下注截至时间
	local_team: string // 主队名字
	local_logo?: string
	visitor_team: string // 客队名字
	visitor_logo?: string
	total_bet_point: number // 总成交量
	total_bet_limit: number // 总投注上限
	date_type: number // 日期类型, 0.其他, 1.今日, 2.明日
	flag_info: string // 推荐的比分内容 1|1-0|500, 格式："子玩法id|推荐比分|赔率", 1.全场 2.半场
	flag_bet_point: number // 推荐比分投注总额
	flag_bet_limit: number // 推荐比分投注限额
	ft_score: string // 全场比分
	hot_opt_info: string // 热门投注比分信息, 1|1|0-0|10.15%, 格式："子玩法id|选项id|选项名字|投注进度", 1.全场 2.半场
}

export interface GetSoccerMatchListReq extends ErrMsg {
	static_id: string // 唯一ID
	league_id: string // 联赛id
	team_name: string // 队名
	start_time: number // 筛选开始时间
	end_time: number // 筛选截至时间
	page: number
	limit: number
}

export interface GetGameListReq extends ErrMsg {
	game_sum: string
	gclass: number // 分类 默认-1
	gplat: number // 平台 默认-1
	page: number
	page_size: number
}

export interface GetSoccerLeagueListRsp extends ErrMsg {
	list: Array<LeagueInfo> // 联赛列表
	select_ids: Array<string> // 选中的联赛的id列表
	total: number // 联赛总数
}

export interface LeagueInfo extends ErrMsg {
	id: string // League id
	name: string // 英文名
	name_zh: string // 中文名
	pid: number // 等级
	league_logo: string // 联赛图标
	match_count: number // 已开启的比赛场次
	country: string // 联赛所属国家/地区
}

export interface UpdateUserLeagueListReq extends ErrMsg {
	select_ids: Array<string> // 选中的联赛的id列表
}

export interface GetJackPortsListRsp extends ErrMsg {
	ports_list: Array<JackPortsNode>
	ports_sum: number
}

export interface JackPortsNode extends ErrMsg {
	app_id: number
	svr_id: number // 服务商id
	caiJin: string // 彩金金额
}

export interface GetGameWinRecordRsp extends ErrMsg {
	data: Array<GameWinRecord>
}

export interface GameWinRecord extends ErrMsg {
	user_id: number // 用户id
	game_id: number // 游戏id
	point: number // 中奖金额
}

export interface ActivityCfgRsp extends ErrMsg {
	data: Array<ActivityCfg>
}

export interface ActivityCfg extends ErrMsg {
	atype: number
	cfg: any
	status: boolean
	job1?: ActivityJob
	job2?: ActivityJob
	active_text?: { [key: string]: string } //
	second_title?: { [key: string]: string } //
	color_btn: { [key: string]: string } // 按钮颜色
	color_left_down: { [key: string]: string } // 左下颜色
	color_right_up: { [key: string]: string } // 右下颜色
	content_title: { [key: string]: string } // 正文标题
	content_btn_title: { [key: string]: string } // 按钮文字
	lang_name?: { [key: string]: string }
	thum_url?: { [key: string]: string } // 缩略图
	url?: string
	lang_url?: { [key: string]: string }
	name: string //
	loc_url?: string //
	loc_name?: string //
	jump_type: number
	jump_url?: string
	ptype: number
	flag?: number // 标签; 0.无, 1.火爆, 2.新增
	stime?: number //
	etime?: number //
	sort: number // 排序
	count_down?: number
	rules: { [key: string]: string } // 规则说明
	pop_ups: number // 弹窗 0 不弹 1 弹
}

export interface GetMyActivityListRsp extends ErrMsg {
	activity_list: Array<ActivityInfo>
	md5: string
}

export interface ActivityInfo extends ErrMsg {
	atype: number // 活动类型, 值参考constCom.RegisterActivity是注册活动;
	satus: number // 0.不能领取 或者已经领取, 1可以领取
	status: number // 0.不显示, 1.显示
	button_status: number // 0.关闭, 1.显示
	sort: number // 排序
	job1?: ActivityJob //
	job2?: ActivityJob //
	ptype: number //
	active_text?: { [key: string]: string } //
	second_title?: { [key: string]: string } //
	color_btn: { [key: string]: string } // 按钮颜色
	color_left_down: { [key: string]: string } // 左下颜色
	color_right_up: { [key: string]: string } // 右下颜色
	content_title: { [key: string]: string } // 正文标题
	content_btn_title: { [key: string]: string } // 按钮文字
	lang_name?: { [key: string]: string }
	thum_url?: { [key: string]: string } // 缩略图
	url?: string
	lang_url?: { [key: string]: string }
	jump_type: number // 按钮功能
	jump_url?: string // 跳转内容
	en_url?: string //
	en_name?: string //
	loc_url?: string //
	loc_name?: string //
	flag?: number // 标签; 0.无, 1.火爆, 2.新增
	stime?: number //
	etime?: number //
	pop_ups?: number // 弹窗状态; 0.不弹窗, 1.每次登录弹窗, 2.每天第一次登录弹窗
}

export interface ActivityJob extends ErrMsg {
	type: number
	info: string
	name: string
}

export interface ReceivActivityAwardReq extends ErrMsg {
	atype: number // 活动ID
	type: number // 类型 0 默认 转盘需要 1白银 2黄金 3砖石
	key: number
}

export interface ReceivActivityAwardRsp extends ErrMsg {
	atype: number // 活动ID
	award: number // 活动奖励金额
	award_type: number // 奖励类型
	coin: number // 积分
	count: number // 剩余次数
	ptype: number // 活动子类型 （转盘用） 1 普通 2 高级 3 周
	num: number // 第几个
	end_time: number
}

export type GetActivityAwardRecordReq = ErrMsg

export interface GetActivityAwardRecordRsp extends ErrMsg {
	data: Array<GetActivityAwardRecordInfo>
}

export interface GetActivityAwardRecordInfo extends ErrMsg {
	id: number
	uid: string
	pic: string
	ptype: number
	point_name: string
	point: number
}

export interface GetShareAgentReq extends ErrMsg {
	ctype: number // 类型, GetShareAgentType; 1推荐福利, 2存款福利
}

export interface GetShareAgentInfoRsp extends ErrMsg {
	reg_num: number // 邀请注册
	reg_succ: number // 注册成功
	all_point: number // 总彩金
	available: number // 可领取
	share_down_config: ShareDownActivityInfo
	share_pay_config: SharePayActivityInfo
}

export interface ShareDownActivityInfo extends ErrMsg {
	stime: number
	etime: number
	down_give_point: number // 下级固定的赠送金额
	pay_point: number // 玩家当天必须大于这个充值金额
	list: Array<ShareDownItem>
}

export interface ShareDownItem extends ErrMsg {
	num: number // 人数
	reward: RewardCfg // 奖励
	total_point: number // 累计彩金
}

export interface SharePayActivityInfo extends ErrMsg {
	stime: number
	etime: number
	list: Array<SharePayItme>
}

export interface SharePayItme extends ErrMsg {
	pay_point: number // 首充金额
	reward: RewardCfg // 奖励
	code_rate: number // 打码倍数
}

export interface GetShareAgentRsp extends ErrMsg {
	available: number // 领取的彩金
}

export interface GetActivityCoinReq extends ErrMsg {
	page: number
	page_size: number
	start: number
	end: number
}

export interface GetActivityCoinRsp extends ErrMsg {
	total: number
	list: Array<GetActivityCoin>
}

export interface GetActivityCoin extends ErrMsg {
	itime: number // 时间戳
	coin: number // 积分
	type: number // 类型
}

export interface GetActivityRecordReq extends ErrMsg {
	page: number
	page_size: number
	start: number
	end: number
	atype: number // 活动ID
}

export interface GetActivityRecordRsp extends ErrMsg {
	total: number
	list: Array<GetActivityRecord>
}

export interface GetActivityRecord extends ErrMsg {
	itime: number // 时间戳
	atype: number // 活动ID
	ptype: number // 转盘类型 金 银
	point: number // 金币
	name: string
}

export interface GetShareInviteSummaryRsp extends ErrMsg {
	register_count: number // 推广注册总人数
	give_point: number // 推广首充返奖总额
	deposit_count: number // 推广首充总人数
	total_commi: number // 历史流水返佣总额
	today_commi: number // 今日流水返佣金额
	yesterday_register_count: number // 昨日推广注册人数
	yesterday_give_point: number // 昨日推广首充返奖金额
	yesterday_deposit_count: number // 昨日推广首充人数
	yesterday_commi: number // 昨日流水返佣金额
}

export interface GetShareFirstPayPidBackRecordReq extends ErrMsg {
	page: number
	page_size: number
	start: number // 开始时间
	end: number // 结束时间
}

export interface GetShareFirstPayPidBackRecordRsp extends ErrMsg {
	total: number // 数据条数
	list: Array<ShareFirstPayPidBackRecord> // 数据记录列表
	total_point: number // 推广首充返佣总金额
}

export interface ShareFirstPayPidBackRecord extends ErrMsg {
	itime: number // 发放时间
	user_id: string // 受邀请人的id
	bill_no: string // 发送订单号
	deposit_point: number // 首存金额
	give_point: number // 奖励金额
}

export interface ActivityReq extends ErrMsg {
	atype: number // 活动key
}

export interface GetDetailsRsp extends ErrMsg {
	details: any
}

export interface GetUnderUserDepositAgentRecordReq extends ErrMsg {
	page: number
	page_size: number
	user_id: number
	user_type: number // 1 直属下级（2级） 2 非直属下级
	time_type: number // 1 当天 2 最近7天 3 最近60天 0 所有
}

export interface GetUnderUserDepositAgentRecordRsp extends ErrMsg {
	total: number // 数据总条数
	list: Array<UserDepositAgentRecord> // 数据列表
}

export interface UserDepositAgentRecord extends ErrMsg {
	user_id?: number // 用户id
	pid?: number // 父级id
	_?: number // 三级父id
	level: number // 用户层级 2/3
	_?: number // 父级id
	_?: number // 三级父id
	level: number // 用户层级 2/3
	uid: string // 用户id字符串
	nick_name: string // 昵称
	register_time: number // 注册时间
	deposit_count: number // 充值人数
	deposit_point: number // 充值总金额
	deposit_give_point: number // 首充返佣总额
	flow: number // 流水
	commi_give_point: number // 流水返佣总额
	total_give_point: number // 返佣总金额
}

export interface GetAgentCommiRsp extends ErrMsg {
	list: Array<GAgentLevel>
}

export interface GAgentLevel extends ErrMsg {
	id: number
	app_id: number
	name: string
	min_point: number
	max_point: number
	commi: number
	info: string
}

export interface GetAgentShareReq extends ErrMsg {
	share_url: string
}

export interface GetAgentShareRsp extends ErrMsg {
	week_flow: number
	week_unter_flow: number
	week_team_flow: number
	week_start_time: string
	week_end_time: string
	day_unter_flow: number
	day_team_flow: number
	unter_num: number
	new_unter_num: number
	team_num: number
	new_team_num: number
	share_url: string
}

export interface GetTeamInfoRsp extends ErrMsg {
	all_user: number
	unter_user: number
	team_user: number
	week_new_user: number
	day_new_user: number
	pid: number
}

export interface GetTeamInfoListReq extends ErrMsg {
	user_id: number
	page: number
	limit: number
}

export interface GetTeamInfoList extends ErrMsg {
	user_id: number
	name: string
	is_new: number
	week_self_flow: number
	week_all_flow: number
	all_user: number
}

export interface GetTeamInfoListRsp extends ErrMsg {
	page: number
	limit: number
	total: number
	list: Array<GetTeamInfoList>
}

export interface QueryTeamUserReq extends ErrMsg {
	user_id: number
}

export interface QueryTeamUserRsp extends ErrMsg {
	user_id: number
	name: string
	pid: number
	last_login_time: string
	register_time: string
	week_flow: number
	week_unter_flow: number
	week_team_flow: number
	unter_user: number
	team_user: number
	all_user: number
}

export interface GetCommiInfoRsp extends ErrMsg {
	week_commi: number // 测
	day_unter_commi: number // 测
	send_unter_commi: number
	yesterday_unter_commi: number
	week_team_commi: number // 测
	last_week_team_commi: number
}

export interface GetCommiInfoListReq extends ErrMsg {
	page: number
	limit: number
}

export interface GetCommiInfoList extends ErrMsg {
	time: string
	ctype: number // 0直属 1团队
	point: number
}

export interface GetCommiInfoListRsp extends ErrMsg {
	page: number
	limit: number
	total: number
	list: Array<GetCommiInfoList>
}

export interface GetFlowInfoListReq extends ErrMsg {
	user_id: number
}

export interface GetFlowInfoList extends ErrMsg {
	time: string
	total_flow: number
	unter_flow: number
	team_flow: number
}

export interface GetFlowInfoListRsp extends ErrMsg {
	user_id: number
	name: string
	list: Array<GetFlowInfoList>
}

export interface GetFlowBackCommiRsp extends ErrMsg {
	list: Array<GFlowLevel>
	day_flow: number
}

export interface GFlowLevel extends ErrMsg {
	id: number
	app_id: number
	name: string
	min_point: number
	max_point: number
	commi: number
	info: string
}

export interface GetFlowBackRecordInfo extends ErrMsg {
	send_time: string
	flow: number
	commi: number
	rate: number
	status: number
	get_time: string
	idate: number // 领取时候用
}

export interface GetFlowBackRecordRsp extends ErrMsg {
	list: Array<GetFlowBackRecordInfo>
}

export interface GetFlowBackPointReq extends ErrMsg {
	idate: number
}

export interface GetFlowBackPointRsp extends ErrMsg {
	point: number
}

export interface GetDayAgentCommiRsp extends ErrMsg {
	list: Array<GAgentLevel>
}

export interface GetDayAgentShareReq extends ErrMsg {
	share_url: string
}

export interface GetDayAgentShareRsp extends ErrMsg {
	pid: number // 上级
	team_num: number // 今天新增团队人员
	day_team_flow: number // 今天下属业绩
	unter_new_num: number // 直属新增
	day_unter_flow: number // 今天直属业绩
	ye_total_flow: number // 昨天总业绩
	ye_commi: number // 昨天总佣金
	today_commi: number // 今日佣金
	total_commi: number // 历史总佣金
	read_commi: number // 可领取
	url: string
	type: number
}

export interface GetDayAgentTeamInfoReq extends ErrMsg {
	user_id: number // 0 全部
	page: number
	limit: number
}

export interface GetDayAgentTeamInfo extends ErrMsg {
	user_id: number
	name: string
	unter_flow: number
	team_flow: number
	commi: number
	team_num: number
}

export interface GetDayAgentTeamInfoRsp extends ErrMsg {
	all_user_num: number // 总人数
	unter_user_num: number // 直属
	team_user_num: number // 其他
	total_flow: number // 总业绩
	data: Array<GetDayAgentTeamInfo>
	page: number
	limit: number
	total: number
}

export interface GetDayFlowInfoListReq extends ErrMsg {
	page: number
	limit: number
}

export interface GetDayFlowInfoList extends ErrMsg {
	time: string
	total_flow: number
	unter_flow: number
	team_flow: number
	commi: number
}

export interface GetDayFlowInfoListRsp extends ErrMsg {
	list: Array<GetDayFlowInfoList>
	page: number
	limit: number
	total: number
}

export interface SeachSelfTeamUserReq extends ErrMsg {
	user_id: number
}

export interface SeachSelfTeamUserRsp extends ErrMsg {
	user_id: number
	name: string
	pid: number
	last_login: string
	level: number
	flow: number
	team_num: number
	team_flow: number
}

export interface GetDayAgentRecordReq extends ErrMsg {
	page: number
	limit: number
	stime: number // 开始时间
	etime: number // 截止时间
}

export interface GetDayAgentRecordRsp extends ErrMsg {
	page: number
	limit: number
	total: number
	data: Array<GetDayAgentRecordInfo> // 数据记录列表
}

export interface GetDayAgentRecordInfo extends ErrMsg {
	read_time: string // 领取时间
	read_point: number // 领取金额
	read_date: string // 领取日期
}

export interface GetDayAgentRsp extends ErrMsg {
	get_point: number
}

export interface GetDayFlowBackRecordInfo extends ErrMsg {
	id: string // 领取奖励是发该ID
	send_time: string // 发放时间
	flow_point: number // 流水金额
	send_rate: string // 返利比例
	send_point: number // 发放金额
	status: number // 领取状态 -1 已过期 0 可领取 1 已领取
}

export interface GetDayFlowBackRecordRsp extends ErrMsg {
	total: number
	data: Array<GetDayFlowBackRecordInfo>
}

export interface GetDayFlowBackReq extends ErrMsg {
	id: string
}

export interface GetNewDayAgentRecordInfoRsp extends ErrMsg {
	page: number
	limit: number
	total: number
	data: Array<GetNewDayAgentRecordInfo> // 记录列表
	total_point: number // 返利总额
}

export interface GetNewDayAgentRecordInfo extends ErrMsg {
	from_user: number // 下级用户id
	itime: number // 领取时间
	order_id: string // 订单id
	detail: Array<GAgentDetalInfo> // 佣金明细
	point: number // 返佣金额
	from_user_str: string // 下级用户名
}

export interface GAgentDetalInfo extends ErrMsg {
	gclass: number // 游戏类型
	commi: number // 返佣金额
	flow: number // 流水
	rate: number // 返佣比例
}

export interface GetConfigRsp extends ErrMsg {
	game_list: Array<TAppGameNode>
	game_sum: string
	pay_type: Array<PayTypeRsp>
	custome_service: Array<SCustomeService>
	custome_sum: string
	notify: number // 0不弹 1弹
	custome_service_type: number // 客服模式 0弹窗模式1外部链接模式
	lun_bo: Array<GetLunBoListInfo> // 轮播配置
	bind_point: number
	back_point: SendBackPoint
	back_point_status: number
	per_cent_point: number // 有可以领取的金额
	commi_type: number // 0流水返利模式1税收返利模式
	activity_list: Array<ActivityInfo> // 活动列表
	top_active: number // 活动中心是否弹窗
	percent_rate: number // 税收比例
	self_rate: number // 自营返利比例
	top_config: Array<TopConfg> // 常驻按钮配置
	give_cfg: GivePointCfg // 赠送金额配置信息
	vip_cfg: Array<SVipConfig> // vip 配置
	vip_reward: number // vip是否发送奖励 0 不发 1发
	is_vip_reward: number // 是否有vip奖励可以领取
	self_pack_url: string // 渠道推广地址
	new_pay_info: Array<NewPayTypeRsp> // 新支付
	share_get_point: number
	app_name: string
	notify_popup: number // 活动公告 0不弹1弹窗
	share_popup: number // 推广中心 0不弹1弹窗
	mail_popup: number // 邮件弹窗 0不弹1弹窗
	bind_popup: number // 绑定送礼弹窗 0不弹1弹窗
	agent_divide_popup: number // 代理分红弹窗 0不弹1弹窗
	open_account_popup: number
	rank_type: number // 1今日盈利榜/本周盈利榜 2本周佣金榜/今日盈利榜
	three_sgin_status: number // 3日签到任务
	point_ratio: number // APP配置的金币比例
	ids: Array<number>
	is_sms: boolean // 是否开启短信验证
	new_customer_service: Array<NewGetCustomerServiceInfo>
	task_open_status: number // 任务系统开关; 0.关闭,1.开启
}

export interface GetGameTypeListRsp extends ErrMsg {
	ids: Array<number>
}

export interface GetGameListRsp extends ErrMsg {
	game_list: Array<TAppGameNode>
	game_sum: string
}

export interface TAppGameNode extends ErrMsg {
	//	Appid  int32  `json:"appid,omitempty"`
	game_id?: number
	name?: string
	gplat?: number
	gclass: number // 游戏种类
	direction?: number // 方向横竖屏 1. 横屏  2. 竖屏
	jump?: number // 跳转方式（区分有无返回） 1. 外部链接 2. iframe
	adapter?: number // 特殊适配 0. 无适配 1. ios适配
	icon?: string // 游戏图标
	special_icon?: string // 特殊图标
	demo?: boolean // true 开启试玩
	//LangName    map[string]string `json:"lang_name,omitempty"`    // 游戏图标//Rules  []*TAppGameRule  `json:"rules"`
	levels?: Array<TAppGameLevel>
	status?: number
	top?: number
	top2?: number
	power?: number
	href?: string
	hb_tag?: number // 火爆 大于0表示开启标识
	zx_tag?: number // 最新 大于0表示开启标识
	tj_tag?: number // 推荐
	gtype: number
	version?: string
	auto_down?: number // 自动下载  1 自动下载  0 不自动下载
	update_url?: string
	hit_update?: GameHitUpdate
	pos?: number
	ids?: Array<number>
}

export interface PayTypeRsp extends ErrMsg {
	pay_type: string // 系统充值类型, SysPayType; 1.VIP充值, 2.线上充值, 3.银行卡充值, 4.赠送, 5.小额支付, 6.专享支付, 7.USDT充值
	pay_key?: Array<string>
	pay_num_list?: Array<number>
	url?: string
	card_name?: string
	card_no?: string
	card_type_name?: string
	open_type?: number
	jump_type?: number
	sale_status: number
	sale_text: string
	sale_num: number
	text: string
	text2: string
	list?: Array<GAppVipPay>
}

export interface GAppVipPay extends ErrMsg {
	app_id: number
	name: string
	wx: string
	wx_2: string
	qq: string
	ali: string
	aite: string
	describes: string
	data: string // 网站跳转地址
	type: number // 跳转类型 0默认打开微信 1跳转网页 2跳转qq 3live800地址
	pay_type: Array<number> // 支持的支付类型 支持的支付类型1微信2支付宝3银行卡
	ext_type: Array<number> // 支持的扩展类型 1官方认证，1花呗.信用卡
	head_url: string // 头像地址描述
	live_800: string // live800地址
}

export interface NewPayTypeRsp extends ErrMsg {
	app_id: number
	name: string
	pay_key: string
	tip_status: number
	tip: string
	sale_num: number
	dest: string
	rand_sort: number // 页签内是否随机排序  0默认是 1 否
	data: Array<{ [key: string]: any }>
}

export interface SCustomeService extends ErrMsg {
	data_id: number
	key: number // 客服标识//10000  联系客服 10001 充值客服 10002 财富客服
	button: string // 客服按钮描述
	status: number // 客服状态0不可用1可用
	type: number // 模式0外部链接 1弹窗模式 2 页签模式 3艾特客服
	url: string // 外部链接
	aite_url: string // 外部链接
	show_img: string
	info1: number // 0不启用1微信2qq3公众号
	data1: string // 账号1
	info2: number // 0不启用1微信2qq3公众号
	data2: string // 账号2
	info3: number // 0不启用1微信2qq3公众号
	data3: string // 账号2
	info4: number // 0不启用1微信2qq3公众号 4艾特
	data4: string // 账号2
	page_sign: Array<number> // 页签状态
	online: Array<string> // 在线配置
	online_info: Array<string> // 在线配置
	wx: Array<string> // 微信
	wx_info: Array<string> // 微信
	ali: Array<string> // 阿里
	ali_info: Array<string> // 阿里
	pub: Array<string> // 公众号
	pub_info: Array<string> // 公众号
	at: Array<string> // 阿特
	at_info: Array<string> // 阿特
	qq: Array<string> // qq
	qq_info: Array<string> // qq
	general_1: Array<number>
	general_2: Array<number>
	general_3: Array<number>
	general_4: Array<number>
}

export interface GetLunBoListInfo extends ErrMsg {
	id: number
	app_id: number
	lunbo_id: number // 图片标识
	desc?: string // 描述
	jump_type: number // 0 不跳转 1 跳转子游戏
	jump_url?: string // 跳转内容 url
	status: number
	sort: number
	opt: number
	itime: number
}

export interface TopConfg extends ErrMsg {
	id: number
	top_id: number
	sort: number
	status: number
	desc?: string
}

export interface GivePointCfg extends ErrMsg {
	reg_point: number // 注册送金
	bind_point: number // 绑定送金
}

export interface SVipConfig extends ErrMsg {
	id: number // id
	app_id: number // app_id
	vip: number // vip等级
	vip_coin: number // vip积分
	stage_id: number // 层级id
	cfg: string // 特权配置
	bet_limit: number // 投注限红
	point: number // vip赠送金额
	code_rate: number // 打码量倍数
}

export interface NewGetCustomerServiceInfo extends ErrMsg {
	app_id: number // 盘口id
	key: number // 客服标识//10000  登录客服  10001 推广界面客服   10002 游戏大厅客服
	button?: string // 客服按钮描述
	status: number // 客服状态0不可用1可用
	update_time?: string // 更新时间
	url1: string // 外部链接1
	url2: string // 外部链接2
	url3: string // 外部链接3
	url4: string // 外部链接4
	lang_name_1: { [key: string]: string } // 名字1
	lang_name_2: { [key: string]: string } // 名字2
	lang_name_3: { [key: string]: string } // 名字3
	lang_name_4: { [key: string]: string } // 名字4
	type_1: number // 图标1
	type_2: number // 图标2
	type_3: number // 图标3
	type_4: number // 图标4
}

export interface SendBackPoint extends ErrMsg {
	idate: number
	point: number
}

export interface GetPayConfigRsp extends ErrMsg {
	need_bind_phone: boolean
	new_pay_info: Array<NewPayTypeRsp> // 新支付
	usdt_rate: number // USDT兑换法币的汇率, *100
}

export interface GetGameRouteReq extends ErrMsg {
	gid: number
	gsc: string
	glv: string
	app_version: string
	game_skin: string // 子游戏皮肤 字符串
	locker?: LockT
	device: ClientDevInfo
	old_app_id: number
}

export interface GetGameRouteRsp extends ErrMsg {
	locker?: LockT
	routes?: Array<TServer>
	mods?: Array<string>
	version?: string // 游戏版本
}

export interface LockT extends ErrMsg {
	ret?: number
	action?: number
	opt?: number
	_uid?: number
	_appid?: number
	_packno?: number
	_svr_t?: string
	_svr_id?: number
	_gid?: number
	_gsc?: string
	_glv?: string
	_gt?: number
	_chair?: number
	time?: number
	ext?: string
}

export interface ClientDevInfo extends ErrMsg {
	device_id?: string // 设备ID
	phone_model?: string // 手机型号 iphone6s
	phone_device_brand?: string // 设备厂商
	os_type?: number // 1 web 2 android 3 ios
	os_version?: string // 系统版本号
	app_version?: string // 客户端版本号
	op_install_key?: string // 客户端打包的openinstall的key
	eare?: string // 地理信息,后续客户端通过gps接口获取
	reg_info?: string // 设备信息
	sign: string // 设置签名
	server_id: string // 服务端生成UUID
	need_sid: number // 是否需要生成serverID
	wx_key: string // 微信登录的时候使用的微信KEY
	w: number // 屏幕宽
	h: number // 屏幕高
	gv: string // openGL version
	gr: string // openGL renderer
}

export interface Conditoin extends ErrMsg {
	vip: number // vip 等级
	level: number // level 等级
	os_type: number // 手机类型 0全部 2 android 3 ios 4原生
	app_ver: string // APP版本
}

export interface TServer extends ErrMsg {
	id: number
	appId: number
	gameId: number
	uids: Array<number>
	// Uids       string    `json:"-"`
	serverType: number
	serverName: string
	serverId: number
	host?: string
	sad?: string
	port?: number
	us_port?: number
	lo_type?: number
	lo_port?: number
	conditoin: Conditoin
	attr?: any
}

export interface QueryAllLocks extends ErrMsg {
	uid: number
	locks: Array<LockT>
}

export interface GAppMusic extends ErrMsg {
	id: number
	app_id: number
	name: string
	file: string
	flag: number
	singer: string
}

export interface CheckUserTypeUser extends ErrMsg {
	itime: number
	pay_count: number // 充值次数
	pay_sum: number // 充值金额
	put_count: number // 提现次数
	t_pay_count: number // 当日充值次数
	lang: number
	general: number
	pack: number
}

export interface PayNameTip extends ErrMsg {
	name: string
	tip: string
}

export interface GetGameDataReq extends ErrMsg {
	app_id: number
	gid: number
	sum: string
	uid: number
}

export interface GetGameDataRsp extends ErrMsg {
	data: Array<ReportGameData>
	sum: string
}

export interface ReportGameData extends ErrMsg {
	app_id: number // appid
	gid: number // gid
	level: string // level
	level_name: string // 场次名字
	rule: string // rule
	rate_tag: number
	player_count: number // 玩牌人数
	status: number // 当前状态
	update_time: number // 上报时 这个状态的时间
	bet_time: number // 投注时间
	count_down: number // 倒计时
	svr_name: string
	svr_id: number
	sub_config: any // 限红数据
	award_list: Array<any> // 保存历史的开奖结果数据，所有的数据
}

export interface GetGameFreeReq extends ErrMsg {
	app_id: number
	gid: number // 游戏ID
}

export interface FreeCount extends ErrMsg {
	itemID: string // 剩余次数
	total: number // 总次数
	count: number // 剩余次数
	minbet: number // 最低金额10000
	start: number // 开始时间
	end: number // 结束时间
	win?: number // 上次赢钱累加
}

export interface SubsidyPointRsp extends ErrMsg {
	times: number
	point: number
}

export interface DoRechargeRedRsp extends ErrMsg {
	point: number
}

export interface ActiveDailyGiftMoney extends ErrMsg {
	app_id: number // 盘口id
	config: ActiveDailyGiftMoneyCfg // 配置
}

export interface ActiveDailyGiftMoneyCfg extends ErrMsg {
	yesterday_bet: number // 昨日投注
	today_bet: number // 今日投注
	today_pay: boolean // 今日充值
	total_bet: number // 总投注
	last_week_total_bet: number // 截至上周的历史投注
	last_month_total_bet: number // 截至上月的历史投注
	this_week_total_bet: number // 本周投注
	this_month_total_bet: number // 本月投注
	daily: boolean // 日可领
	daily_point: number // 日礼金
	next_daily_point: number // 下一日日礼金
	weekly: boolean // 周可领
	weekly_point: number // 周礼金
	next_weekly_point: number // 下一周礼金
	monthly: boolean // 月可领
	monthly_point: number // 月礼金
	next_monthly_point: number // 下一周礼金
	daily_cfg: Array<GiftMoneyCfg> // 每日配置
	weekly_cfg: Array<GiftMoneyCfg> // 每周配置
	monthly_cfg: Array<GiftMoneyCfg> // 每月配置
}

export interface GiftMoneyCfg extends ErrMsg {
	bet_point: number // 投注金额
	point: number // 赠送礼金
}

export interface DoDailyGiftMoneyReq extends ErrMsg {
	gift_money_type: number // 1 日礼金  2 周礼金  3 月礼金
}

export interface DoDailyGiftMoneyRsp extends ErrMsg {
	point: number
}

export interface VipRewardReq extends ErrMsg {
	level: number
}

export interface CheckVipRewardRsp extends ErrMsg {
	list: Array<CheckVipInfo>
}

export interface CheckVipInfo extends ErrMsg {
	level: number // 等级
	status: number // 是否已经领取
	point: number // 奖励金额
}

export interface VipRewardRsp extends ErrMsg {
	point: number // 可以领取的金额
	status: number // 状态 是否可以领取
}

export interface NewCheckVipRewardRsp extends ErrMsg {
	list: Array<CheckVipInfo>
	week: CheckVip
	month: CheckVip
}

export interface CheckVip extends ErrMsg {
	pay: boolean // 本周/月充值
	last_vip: number // 上周/月vip
	last_point: number // 上周/月礼金
	last_get: boolean // 上周/月礼金领取
	need_code: number // 本周/月需要打码量
	code: number // 本周/月打码量
	now_vip_point: number // 当前等级 周/月礼金
	next_vip_point: number // 下一等级 周/月礼金
}

export interface NewVipRewardReq extends ErrMsg {
	type: number // 0 领取升级彩金 1 领取周礼金 2 领取月礼金
	level: number // 领取升级彩金时传入
}

export interface GetLimitTimeFirstPayActivityCfgRsp extends ErrMsg {
	config: LimitTimeFirstPayActivity
	status: number // 0.结束; 1.未参与; 2.参与,未第二次充值; 3.参与,已经第二次充值;
	data: LimitTimeFirstPayActivityRecord
	put_code: number
	one_code: number
	two_code: number
	three_code: number
	one_point: number
	two_point: number
	three_point: number
	left_time: number // 活动剩余倒计时,单位:秒
}

export interface LimitTimeFirstPayActivity extends ErrMsg {
	stime: number
	etime: number
	limit_hour: number // 限制时间 小时  -1 无倒计时
	delay_min: number // 付款延时时间 分钟
	list: Array<LimitTimeFirstPayActivityCfgItem> // 限时首充返利活动配置项
}

export interface LimitTimeFirstPayActivityCfgItem extends ErrMsg {
	key: number // 档位
	dama_rate: number // 打码量, 比例  90 = 90%
	dama_multi: number // 提现打码倍数限制
	rate: number // 返奖比例, 90 = 90%   =  首充金额 * 返奖比例
	limit_point: number // 返奖最高限额,单位:元/10000
	min_point: number // 参加活动最低金额,单位:元/10000
}

export interface LimitTimeFirstPayActivityRecord extends ErrMsg {
	app_id: number
	uid: number // 用户id
	idate: number // 生成任务日期
	itime: number // 生成任务时间
	point: number // 任务金额, 单位:元/10000
	re_pay: number // 次日充值 0 未充值  1 充值
	one_lv: number // 1档任务奖励领取状态, 0.未领取, 1.领取
	two_lv: number // 2档任务奖励领取状态, 0.未领取, 1.领取
	three_lv: number // 3档任务奖励领取状态, 0.未领取, 1.领取
	one_point: number // 1档任务金额, 单位:元/10000
	two_point: number // 2档任务金额, 单位:元/10000
	three_point: number // 3档任务金额, 单位:元/10000
}

export interface GetGiftCodeRewardReq extends ErrMsg {
	code: string // 礼包码
}

export interface GetGiftCodeRewardRsp extends ErrMsg {
	item_id: number // 礼包码编号
	code: string // 礼包码
	reward_type: number // 奖励类型
	reward_point: number // 奖励金币数量
	deposit_discount_rate: Array<GiftCodePayBackReward> // 奖励存款优惠-比例列表
	deposit_discount_value: Array<GiftCodePayBackReward> // 奖励存款优惠-固定列表
	flow_multi: number // 流水倍数
	close_time: number // 结束时间,0.永远有效
	get_point: number // 最终获得金额,单位:分/10000
}

export interface GiftCodePayBackReward extends ErrMsg {
	value: number // 存款奖金比例/金额, *10000
	join_point: number // 参加金额,单位:元/10000
	limit_point: number // 最高限额,单位:元/10000
}

export interface GetGiftCodePayBackCfgRsp extends ErrMsg {
	list: Array<GiftCodePayBackCfg>
	total: number
}

export interface GiftCodePayBackCfg extends ErrMsg {
	id: string // id
	group_id: number // 规则id
	lang_name: string // 优惠名称,多语言json字符串
	reward_type: number // 奖励类型,参考constCom.GiftCodeRewardType
	pay_back_reward_rate: Array<GiftCodePayBackReward> // 奖励存款优惠-比例列表
	pay_back_reward_value: Array<GiftCodePayBackReward> // 奖励存款优惠-固定列表
	flow_multi: number // 流水倍数
	close_time: number // 结束时间戳; 0.没有时间限制
	used_time: number // 使用时间戳
	left_time: number // 剩余倒计时,单位:秒
}

export interface GetDepositBonusDataRsp extends ErrMsg {
	first_pay_act_cfg: GetLimitTimeFirstPayActivityCfgRsp // 限时首充返利配置
	gift_code_cfg_list: Array<GiftCodePayBackCfg> // 礼包码充值优惠列表
	promo_item_list: Array<UserPromoItem> // 优惠道具列表
	gift_code_count: number // 礼包码充值优惠个数
	promo_item_count: number // 优惠道具个数
	min_left_time: number // 优惠最快结束倒计时,单位:秒
}

export interface RechargeRed extends ErrMsg {
	app_id: number
	config: Array<ActiveRechargeRedCfg>
}

export interface ActiveRechargeRedCfg extends ErrMsg {
	point: number
	weight: number
}

export interface RechargeRedRsp extends ErrMsg {
	is_show: boolean
	stime: number
	etime: number
}

export interface SubsidyPointCfg extends ErrMsg {
	user_vip: { [key: string]: SubsidyPointUvipCfg }
	status: number
	limit_amount: number
	self_times: number
	stime: number
	etime: number
}

export interface SubsidyPointUvipCfg extends ErrMsg {
	times: number
	point: number
}

export interface GetSelfShareReq extends ErrMsg {
	share_url: string
}

export interface GetSelfShareRsp extends ErrMsg {
	url: string // 地址
	ys_total_point: number // 昨天总
	ys_unter_point: number // 昨天直属
	ys_other_point: number // 昨天其他
	unter_num: number // 直属人数
	other_num: number // 其他人数
	total_point: number // 总奖励
	read_point: number // 可以领取奖励
	pid: number // 上级id
	total_self_point: number // 总得自营反水
	ys_self_point: number // 昨天自营
	read_self_point: number // 可以领取得 自营反水
	type: number // 是否是短地址 1 是0不是
}

export interface GetSelfReadRecordReq extends ErrMsg {
	page: number
	limit: number
}

export interface GetSelfReadRecordInfo extends ErrMsg {
	read_time: string
	read_point: number
	read_type: number
}

export interface GetSelfReadRecordRsp extends ErrMsg {
	page: number
	limit: number
	total: number
	data: Array<GetSelfReadRecordInfo>
}

export interface GetSelfReadRsp extends ErrMsg {
	get_point: number
}

export interface GetSelfTeamReq extends ErrMsg {
	page: number
	limit: number
}

export interface GetSelfTeamInfo extends ErrMsg {
	user_id: number
	name: string
	is_new: number // 1 是新增
	percent: number // 税收
	team_num: number // 团队人数
	team_percent: number // 团队人数
}

export interface GetSelfTeamRsp extends ErrMsg {
	team_num: number // 总人数
	unter_num: number // 直属人数
	other_num: number // 其他人数
	new_unter_num: number // 今日新增直属
	new_other_num: number // 今天新增其他人数
	page: number
	limit: number
	total: number
	data: Array<GetSelfTeamInfo>
}

export interface SeachSelfTeamReq extends ErrMsg {
	user_id: number
}

export interface SeachSelfTeamRsp extends ErrMsg {
	user_id: number
	name: string
	pid: number
	last_login: string
	level: number
	percent: number
	team_num: number
	team_percent: number
}

export interface GetSendRecordReq extends ErrMsg {
	page: number
	limit: number
}

export interface GetSendRecordInfo extends ErrMsg {
	send_time: string
	unter_point: number
	other_point: number
	total_point: number
	self_point: number
	belong: number
}

export interface GetSendRecordRsp extends ErrMsg {
	page: number
	limit: number
	total: number
	data: Array<GetSendRecordInfo>
	week_total_send_point: number
	week_unter_send_point: number
	week_other_send_point: number
	week_self_send_point: number
}

export interface BindPidReq extends ErrMsg {
	pid: number
}

export interface GetSelfAgentInfoRsp extends ErrMsg {
	yesterday_point: number // 昨日佣金
	yesterday_real_count: number // 昨日新增有效人数
	today_real_count: number // 今日有效人数
	total_point: number // 总佣金
	down_count: number // 下级人数
	under_count: number // 直属人数
	team_count: number // 团队人数
	read_point: number // 可以领取奖励
	rate: number // 佣金比例
	total_bet_point: number // 下级总的投注
}

export interface GetSelfDownTeamInfoReq extends ErrMsg {
	page: number
	limit: number
	user_id: number
}

export interface GetSelfDownTeamInfoRsp extends ErrMsg {
	total: number
	list: Array<GetSelfDownTeamInfo>
}

export interface GetSelfDownTeamInfo extends ErrMsg {
	uid: number // UID
	total_point: number // 总贡献佣金
	total_bet_point: number // 总投注
	yesterday_point: number // 昨日贡献佣金
}

export interface GetPromoItemListReq extends ErrMsg {
	page: number
	limit: number
	item_type: number // 道具类型,参考constCom.PromoItemType定义
	used_status: number // 使用状态,参考constCom.PromoItemUsedStatus定义; -1.全部, 0.未使用, 1.使用中, 2.已使用, 3.已过期
}

export interface GetPromoItemListRsp extends ErrMsg {
	list: Array<UserPromoItem>
	total: number
}

export interface UserPromoItem extends ErrMsg {
	item_id: number // 道具编号
	cfg_id: number // 道具配置编号
	end_time: number // 过期时间, 0.不会过期
	used_status: number // 使用状态,参考constCom.PromoItemUsedStatus定义; 0.未使用, 1.使用中, 2.已使用, 3.已过期
	used_time?: number // 使用时间
	cfg_data?: string // 道具配置json数据
	cfg: PromoItemCfg // 道具配置
	left_time: number // 剩余时间倒计时,单位:秒
}

export interface PromoItemCfg extends ErrMsg {
	app_id: number
	cfg_id: number // 配置编号
	item_type: number // 道具类型,参考constCom.PromoItemType定义
	status: number // 状态; 0.禁用, 1.启用
	repeat_use: number // 是否可重复使用; 0.否, 1.是
	direct_use: number // 是否可直接使用; 0.否, 1.是
	item_lang: string // 多语言配置json字符串, map[int32]PromoItemLang
	deposit_reward_cfg?: DepositRewardItemCfg // 存款优惠道具配置
	point_add_cfg?: PointPromoItemCfg // 金币道具配置
	zhuan_pan_cfg?: ZhuanPanPromoItemCfg // 转盘道具配置
	vip_point_multi_cfg?: VipPointMultiItemCfg // VIP积分加倍道具配置
	vip_point_add_cfg?: VipPointAddItemCfg // VIP积分道具配置
}

export interface DepositRewardItemCfg extends ErrMsg {
	reward_type?: number // 优惠类型, 0.固定值, 1.比例
	dama_multi?: number // 打码倍数
	limit_hour?: number // 时间限制,单位:小时; 0.不限制
	reward_list?: Array<PayPromoItemRewardCfg> // 奖励配置
}

export interface PayPromoItemRewardCfg extends ErrMsg {
	join_point?: number // 参加金额,*10000
	value?: number // 存款奖励金额/比例,*10000
	limit_point?: number // 最高限额,*10000
}

export interface PointPromoItemCfg extends ErrMsg {
	dama_multi?: number // 打码倍数
	point?: number // 奖励金币金额,*10000
}

export interface ZhuanPanPromoItemCfg extends ErrMsg {
	coin?: number // 转盘积分
}

export interface VipPointMultiItemCfg extends ErrMsg {
	duration?: number // 持续时间,单位:分钟
	multi_num?: number // vip积分获得倍数
}

export interface VipPointAddItemCfg extends ErrMsg {
	vip_point?: number // 奖励的vip积分,*100
}

export interface UsePromoItemReq extends ErrMsg {
	item_id: number // 道具编号
}

export interface UsePromoItemRsp extends ErrMsg {
	item_id: number // 道具编号
	used_status: number // 使用后的状态, 0.未使用, 1.使用中, 2.已使用
	end_time: number // 道具过期时间
	reward_point: number // 金币奖励
	reward_vip_point: number // vip积分奖励
	reward_coin: number // 转盘积分奖励
}

export interface PromoItemUseRecordReq extends ErrMsg {
	page: number
	limit: number
}

export interface PromoItemUseRecordRsp extends ErrMsg {
	page: number
	limit: number
	total: number
	data: Array<PromoItemUseRecordData>
}

export interface PromoItemUseRecordData extends ErrMsg {
	app_id: number
	item_id: number // 道具编号
	cfg_id: number // 道具配置编号
	item_type: number // 道具类型,参考constCom.PromoItemType定义
	repeat_use: number // 是否可重复使用; 0.否, 1.是
	direct_use: number // 是否可直接使用; 0.否, 1.是
	user_id: number // 用户id
	user_name: string // 玩家昵称
	used_status: number // 使用状态,参考constCom.PromoItemUsedStatus定义; 0.未使用, 1.使用中, 2.已使用, 3.已过期
	used_time: number // 使用时间
	finish_time: number // 使用完成时间
	end_time: number // 过期时间; 0.不会过期
	pack_no: number // 渠道id
	pack_name: string // 渠道名称
	reward_status: number // 奖励发放状态; 0.未发放,1.已发送
	reward_time: number // 奖励发放时间
	reward_point: number // 奖励的金币
	reward_vip_point: number // 奖励的vip积分
	reward_coin: number // 奖励的转盘积分
	remark: string // 备注
	item_lang: string // 多语言配置json字符串, map[int32]PromoItemLang
}

export interface GetMyTaskActivityInfoReq extends ErrMsg {
	task_id: string
}

export interface GetMyTaskActivityInfoRsp extends ErrMsg {
	task_point: number // 任务积分
	task_point_left_time: number // 任务积分重置倒数时间
	day_left_time: number // 每日任务倒计时
	week_left_time: number // 每周任务倒计时
	month_left_time: number // 每月任务倒计时
	list: Array<GetMyTaskActivityCfgInfo> // 用户的任务信息列表
	progress: Array<UserTaskPointRewardItem> // 用户的任务积分奖励领取进度
}

export interface GetMyTaskActivityCfgInfo extends ErrMsg {
	task_id: string // 任务id
	name: string // 任务名称
	task_type: number // 完成任务类型, 参考constCom.TaskType;
	task_num: number // 完成任务需要的数量
	game_class: number // 指定游戏类型
	game_id: Array<number> // 指定游戏id
	task_point: number // 游戏需要完成的流水
	task_channel: Array<string> // 指定渠道列表
	task_week: number // 任务周期类型; 1.每日任务, 2.每周任务; 3.每月任务; 4.一次性任务
	reward_point: number // 金币奖励数值,单位:元/10000
	reward_task_point: number // 任务积分奖励
	reward_vip_point: number // vip积分奖励
	task_desc: string // 任务描述
	lang_task: { [key: string]: LangTask } // 多语言配置'
	task_self_num: number // 已完成数量
	task_status: number // 任务状态; 0.未完成, 1.已完成未领取, 2.已领取
	sort: number // 排序
}

export interface LangTask extends ErrMsg {
	name: string // 任务名称
	task_desc: string // 任务描述
}

export interface UserTaskPointRewardItem extends ErrMsg {
	need_task_point: number // 需要的任务积分
	reward_point: number // 奖励的金币,单位:元/10000
	reward_vip_point: number // 奖励的vip积分
	dama_multi: number // 金币提现需要的打码量倍数
	status: number // 0.未完成, 1.已完成未领取, 2.已领取
}

export interface GetMyTaskActivityRewardReq extends ErrMsg {
	task_id: string
}

export interface GetMyTaskActivityRewardRsp extends ErrMsg {
	reward_point: number // 金币奖励,单位:元/10000
	reward_task_point: number // 任务积分奖励
	reward_vip_point: number // vip积分奖励
}

export interface GetGameTaskActivityInfoReq extends ErrMsg {
	global_task_type: number
	game_id: number
}

export interface GetGameTaskActivityInfoRsp extends ErrMsg {
	global_task_type: number
	task_id: string
}

export interface GetUserTaskPointRewardReq extends ErrMsg {
	need_task_point: number // 需要的任务积分
}

export interface GetUserTaskPointRewardRsp extends ErrMsg {
	reward_point: number // 奖励的金币,单位:元/10000
	reward_vip_point: number // 奖励的vip积分
}

export interface GetUserInfoRsp extends ErrMsg {
	nickname: string
	headimg: string
	uid: number
	user_type: number // 1游客 没有绑定手机 2 绑定手机了 3微信 4第三方账号
	sphone?: string // 带星号不加密的手机号码
	bank_point: number
	point: number
	vip_coin: number // 当前等级
	vip_level: number // 当前等级
	next_coin: number // 离下一vip差多少
	real_name?: string // 姓名
	account?: string
	phone: string // 手机
	phone_bind: boolean // 手机是否绑定
	email: string // 邮箱
	email_bind: boolean // 邮箱是否绑定
	is_pay: number // 是否充值
	all_put_code: number // 所需要的打码量
	ready_put_code: number // 已经的打码量
	cpf_account: string
	fname: string
	lname: string
	unusual_name: number // 异常的姓名
	birth: string // 生日
	country: string // 国家
	state: string // 区
	city: string // 市
	street_address: string // 街道
	postal_code: string // 邮编
}

export interface GetUserPointRsp extends ErrMsg {
	is_pay: number // 是否充值
	bank_point: number
	point: number
	all_put_code?: number // 所需要的打码量
	ready_put_code?: number // 已经的打码量
}

export interface GetUserWalletInfoRsp extends ErrMsg {
	point: number // 余额
	put_point: number // 可提现金额
	lock_point: number // 锁定金额
	code: number // 需要打码量
	complete_code: number // 已经完成打码量
}

export interface EditUserInfoReq extends ErrMsg {
	real_name?: string // 姓名
	nickname: string
	headimg: string
	birth: string // 生日
	country: string // 国家
	state: string // 区
	city: string // 市
	street_address: string // 街道
	postal_code: string // 邮编
}

export interface EditPwdReq extends ErrMsg {
	acode: string
	phone: string
	code: string
	pwd: string
}

export interface BindPhoneReq extends ErrMsg {
	acode: string
	phone: string
	code: string
	pwd: string
	real_name: string // 真实姓名
}

export interface BindPhoneRsp extends ErrMsg {
	point: number
	phone: string
	bind_point: number
	phone_point: number
}

export interface BindCPFReq extends ErrMsg {
	cpf_account: string
	fname: string
	lname: string
}

export type BindCPFRsp = ErrMsg

export interface BindAccountReq extends ErrMsg {
	account: string
	email: string
	code: string
}

export interface GetPointListReq extends ErrMsg {
	page: number
	page_size: number
	gid: number
}

export interface GetPointListRsp extends ErrMsg {
	total: number
	point_log_list: Array<GetPointListInfo>
}

export interface GetPointListInfo extends ErrMsg {
	point: string
	point_name: string
	time: string
	point_type: number
	hit: string
	game_type: number
}

export interface GetPointRankReq extends ErrMsg {
	type: number // 1 今日盈亏榜 2财富榜 3周排行榜 4 流水日佣金榜 5 税收周佣金榜
	page: number
}

export interface GetPointRankRsp extends ErrMsg {
	my_hit_point: number
	pointRankList: Array<GetPointRankInfo>
	page: number
	my_rank: number // 自己得排名
}

export interface GetBankInfoReq extends ErrMsg {
	bind_type: number
	device: UserPayDevices // 版本信息
}

export interface GetBankInfoRsp extends ErrMsg {
	entrus_bank_account: string
	entrus_bank_user: string
	entrus_bank_name: string
	bank_name?: string // 银行支行
	bank_provcince?: string // 开户省
	bank_city?: string // 开户市
	bank_certificate_code?: string // 银行卡身份证
	// 支付宝信息
	ali_account?: string
	ali_name?: string
	ali_certificate_code?: string // 支付宝身份证
	// 页签开关
	ali_status: number // 支付宝提现 0不可展示 1展示
	bank_status: number // 银行卡提现 0不可展示 1展示
	XinYuan_status: number // 新元助手状态 0不显示 1显示 新元助手只在安卓显示
	XinYuan_fixpoint?: Array<number> // 新元提現金額列表
	ali_min_put_point?: number
	bank_min_put_point: number
	ali_day_max_put_point?: number
	bank_day_max_put_point: number
	ali_max_put_point?: number
	bank_max_put_point: number
	ali_put_server_charge?: number
	ali_put_server_charge_set?: Array<PutServerChargeSetting>
	bank_put_server_charge: number
	bank_put_server_charge_set: Array<PutServerChargeSetting>
	forzen_point: number
	ali_put_day_max_num?: number
	bank_put_day_max_num: number
	min_put_server_charge: number
	// 海外银行卡信息
	over_sea_entrus_bank_account: string // 账号
	over_sea_entrus_bank_user: string // 姓名
	over_sea_entrus_bank_name: string // 银行名字
	over_sea_bank_status: number // 是否打开海外银行卡提现
	over_sea_bank_min_put_point: number // 海外银行卡单笔最小
	over_sea_bank_day_max_put_point: number // 海外银行卡一天最大
	over_sea_bank_max_put_point: number // 海外银行卡单笔最大
	over_sea_bank_put_server_charge: number // 海外银行卡手续费
	over_sea_bank_put_server_charge_set: Array<PutServerChargeSetting>
	over_sea_bank_put_day_max_num: number // 海外银行卡提现次数
	// USDT绑定信息
	usdt_status?: number // USDT提现标签是否显示, 0.不显示, 1.显示
	usdt__min_put_point?: number // USDT单笔最小
	usdt__day_max_put_point?: number // USDT一天最大
	usdt__max_put_point?: number // USDT单笔最大
	usdt__put_server_charge?: number // USDT手续费
	usdt__put_server_charge_set?: Array<PutServerChargeSetting>
	usdt__put_day_max_num?: number // USDT提现次数
	usdt_erc_addr?: string // erc20地址
	usdt_trc_addr?: string // TRC20地址
	usdt_omni_addr?: string // omni地址
	usdt_rate: number // USDT兑换法币的汇率, *100
	// 电子钱包绑定信息
	ewallet_status: number // 电子钱包提现总开关, 0.关闭 1.开启
	ewallet_list: Array<EWalletPutInfo> // 电子钱包列表
	// 巴西提现绑定信息
	bra_pay_status: number // 巴西代付开关, 0.关闭 1.开启
	bra_pay_list: Array<BRAPayPutInfo> // 巴西代付方式列表
	put_code_per_cen: number // 打码量倍数
	lave_put_code: number // 剩余打码量
	put_server_charge_fee: number // 免提现手续费次数
	quick_put_status: number // 快速提现开关 0关闭 1开启
}

export interface EWalletPutInfo extends ErrMsg {
	type: number // 钱包类型
	name: string // 钱包名字
	account: string // 钱包账号/地址
	account_name: string // 钱包用户名
	currency: string // 钱包支持的币种
	status: number // 提现 0不可展示 1展示
	min_put_point: number // 单笔最小
	max_put_point: number // 单笔最大
	day_max_put_point: number // 一天最大
	put_day_max_num: number // 提现次数
	put_server_charge: number // 手续费
	put_server_charge_set: Array<PutServerChargeSetting> //
}

export interface BRAPayPutInfo extends ErrMsg {
	type: number // 提现类型
	name: string // 提现类型名
	bank_account: string // 账号,巴西PIX代付证件传CPF或CNPJ号码
	bank_user: string // 用户名
	entrus_bank_name: string // 銀行名字,巴西PIX代付固定传”PIX”
	bankName: string // 银行支行,巴西PIX代付传账户类型CPF, CNPJ, PHONE, EMAIL, EVP五种之一
	bank_province: string // 开户省,巴西PIX代付证件传CPF或CNPJ号码
	bankCity: string // 开户市,巴西PIX代付传证件类型CPF, CNPJ
	status: number // 状态; 0.不可展示, 1.展示
	min_put_point: number // 单笔最小
	max_put_point: number // 单笔最大
	day_max_put_point: number // 一天最大
	put_day_max_num: number // 提现次数
	put_server_charge: number // 手续费
	put_server_charge_set: Array<PutServerChargeSetting> //
}

export interface BindBankInfoReq extends ErrMsg {
	entrusBankAccount: string
	entrusBankUser: string
	entrusBankName: string
	bankName: string
	bankProvcince: string
	bankCity: string
	certificateCode: string
	bankCode: string
	aliAccount: string
	aliName: string
	bind_type: number // 提现绑定类型; constCom.BindType; 1.银行卡, 2.支付宝, 3.海外银行卡, 4.新元代付, 5.USDT, 6.电子钱包, 7.巴西PIX
	bind_sub_type: number
	usdt_erc_addr?: string // erc20地址
	usdt_trc_addr?: string // TRC20地址
	usdt_omni_addr?: string // omni地址
	code: string // 验证码
	phone: string
	acode: string
}

export interface PostIpInfoReq extends ErrMsg {
	ip: string
	data: string
}

export interface GetProblemReq extends ErrMsg {
	page: number
	limit: number
}

export interface GetProblemInfo extends ErrMsg {
	problem_id: number
	id: number
	problem: string // 问题
	status: number // 状态0为未读1已读2已回复
	answer: string // 回复
}

export interface GetProblemRsp extends ErrMsg {
	page: number
	limit: number
	total: number
	data: Array<GetProblemInfo>
}

export interface SetProblemReq extends ErrMsg {
	type: number // 0 提交 1删除
	problem: string // 问题
	id: number
}

export interface SetSelfCfgReq extends ErrMsg {
	head: number // 0默认
	pao: number // 0默认
}

export interface GetUserShareUrlReq extends ErrMsg {
	url: string
}

export interface GetUserShareUrlRsp extends ErrMsg {
	url: string
	type: number
}

export interface PostInstallGameReq extends ErrMsg {
	game_id: number
	game_name: string
}

export interface CheckVersionReq extends ErrMsg {
	ch: number
}

export interface GetTaskStatusRsp extends ErrMsg {
	num: number
}

export interface GetUserVipListRsp extends ErrMsg {
	vip_level: number // 当前VIP
	down_count: number // 推广人数
	real_count: number // 有效人数
	vip_list: Array<VipListInfo>
	vip_update_coin: number // VIP推广一个人的积分
}

export interface VipListInfo extends ErrMsg {
	vip_level: number // VIP等级
	down_count: number // 推广人数
	vip_coin: number // 所属积分
	bet_limit: number // 限红
}

export interface CollectGameReq extends ErrMsg {
	type: number // 1 收藏 2 取消收藏
	gid: number
}

export interface MyGameListRsp extends ErrMsg {
	collect_gid: Array<number> // 收藏游戏
	recent_gid: Array<number> // 最近游戏
}

export interface CheckVersionRsp extends ErrMsg {
	// 渠道代码
	pack_ext_code?: string
	// 客户端更新提示
	update_notice?: NoticeInfo
	//App              *AppInfo               `json:"app,omitempty"`      //app相关配置//ISSMS            bool                   `json:"is_sms"`             // 是否开启短信验证
	reg_type: number // 注册类型 0都开放  2账号注册 2手机号注册
	currency?: string // 货币类型
	point_ratio: number // APP配置的金币比例
	open_account_popup?: number
	data_hosts?: Array<string> // 客户端data域名数组
	debug?: number // 1 客户端开启debug
	official_url?: string // 官网地址
	lang: Array<number> // 可用语言包
}

export interface GetMsgListReq extends ErrMsg {
	type: number
	lang: number
	flag: number // 0=全部；1=未读；2=已读
}

export interface GetMsgListRsp extends ErrMsg {
	mail_total: number
	notice_tital: number
	notice_total: number
	mail: Array<GetMsgListInfo>
	notice: Array<GetMsgListInfo>
}

export interface GetMsgListInfo extends ErrMsg {
	id: number
	title: string
	content?: string
	itime?: string
	time_unix?: number
	red_status: number
	give_point: number // 赠送金额
	give_status: number // 是否领取
	lang_msg?: { [key: string]: MsgInfo }
	lang_notify?: { [key: string]: NotifyInfo }
	back_url?: string
	jump_type?: number
	jump_text?: string
	jump_param?: string
	lang_mail: { [key: string]: Mail }
}

export interface LangMail extends ErrMsg {
	lang_mail: { [key: string]: Mail }
}

export interface Mail extends ErrMsg {
	mail_title: string
	mail_content: string
	mail_sign: string
}

export interface MsgInfo extends ErrMsg {
	title: string
	content: string
	from: string
}

export interface NotifyInfo extends ErrMsg {
	title: string
	content: string
	from: string
	back_url: string
}

export interface ReadMsgReq extends ErrMsg {
	id: number
	msg_type: number
	read_status: number
	lang: number
}

export interface ReadMsgRsp extends ErrMsg {
	id: number
	title: string
	red_status: number // 1已读 0没读
	give_point: number // 赠送金额
	give_status: number // 是否领取
	content: string
	content_title: string
	back_url: string
	from: string
	send_time: string
	time_unix: number
	end_time: string
	read_time: string
	msg_type: number
	jump_text: string // 按钮文本
	jump_param: string // 跳转参数
	jump_type: number // 跳转类型
}

export interface DelMailReq extends ErrMsg {
	id: number
}

export interface ApplyCashReq extends ErrMsg {
	point: number // 提现金额,单位:元
	type: number // 提现类型, constCom.BindType
	sub_type: number // 提现子类型
	pwd: string // 提现密码
	usdt_type?: number // 1erc 2trc 3omni
	usdt_addr?: string // usdt地址
	usdt_rate: number // 本地货币换U的汇率
	usdt_point: number // 换算的USDT金额
	// 异卡信息提交的参数
	entrus_bank_account?: string // 账号  密
	entrus_bank_user?: string // 账号名称 密
	entrus_bank_name?: string // 银行名称
	bank_name?: string // 银行支行
	bank_provcince?: string // 开户省
	bank_city?: string // 开户市
	app_sdk_data?: string // 上报信息
}

export interface AppleCashRsp extends ErrMsg {
	order_no?: string
	other_bank_name: string // 异卡信息
	other_bank_status: number // == 2的时候判断是异卡需要填写异卡信息
}

export interface ShareGetPointReq extends ErrMsg {
	url: string
	ptype: number // 0.获取分享链接, 1.领取分享活动奖励
}

export interface ShareGetPointRsp extends ErrMsg {
	url: string
	point: number
}

export interface GetSourceTypeRsp extends ErrMsg {
	give_list: Array<PointLogTypeInfo>
}

export interface GetUserBounsListReq extends ErrMsg {
	source_type: Array<number>
	stime: number
	page: number
	limit: number
}

export interface BounsListRsp extends ErrMsg {
	page: number
	limit: number
	total: number
	list: Array<BounsListInfo>
}

export interface BounsListInfo extends ErrMsg {
	ctime: string // 时间
	time_unix: number
	chang_point: number
	opt_code: number // 变更类型
	opt_source: string // 扩展信息
}

export interface UserPointRecordReq extends ErrMsg {
	page: number
	page_size: number
	idate: number
}

export interface UserPointRecordRsp extends ErrMsg {
	total: number
	data: Array<UserPointRecordInfo>
}

export interface UserPointRecordInfo extends ErrMsg {
	ctype: number // 操作类型
	cname: string // 操作类型描述
	itime: string // 时间
	point: number // 金币
	desc: string // 什么游戏 或者是
	time_unix: number
}

export interface UserGameRecordReq extends ErrMsg {
	page: number
	page_size: number
	gclass: number
	stime: number
	etime: number
	gid: number
	glv: string
	is_win: number // 0 全部 1 win 2 loss
}

export interface UserGameRecordRsp extends ErrMsg {
	list: Array<UserGameRecordInfo>
}

export interface UserGameRecordInfo extends ErrMsg {
	gname: string // 游戏名字
	bet: number // 投注
	hit: number // 返奖
	itime: number // 时间戳
	gqh: string // 游戏期号
	gid: number
	level: string
	gd: string
	subs?: any
	bno?: string
}

export interface UserGameRecordSumRsp extends ErrMsg {
	bet: number // 投注
	hit: number // 返奖
}

export interface GetGetGameHistoryRecordReq extends ErrMsg {
	page: number
	page_size: number
	gid: number
	glv: string
}

export interface GetGetGameHistoryRecordRsp extends ErrMsg {
	total: number
	list: Array<GetGetGameHistoryRecordInfo>
}

export interface GetGetGameHistoryRecordInfo extends ErrMsg {
	gname?: string // 游戏名字
	itime: number // 时间戳
	gid: number
	level: string
	gd: string
	subs?: any
	bno?: string
}

export interface ApplyCashListReq extends ErrMsg {
	status: number // 状态 状态  -1 拒绝 1 审核中 3 成功
	date_type: number // 时间范围 0 全部 1 当天 2 最近7天 3 最近60天
	page: number
	page_size: number
}

export interface ApplyCashListRsp extends ErrMsg {
	total: number
	list: Array<ApplyCashListInfo>
}

export interface ApplyCashListInfo extends ErrMsg {
	create_date: string // 时间
	time_unix: number
	account: string // 账号
	point: number // 金额
	usdt_point: number // usdt金额
	status: number // 状态  -1 拒绝  3 成功  其余状态都是审核中
	reason: string // 描述
	type: number // 1 银行卡 2支付宝
}

export interface GetUserPayListReq extends ErrMsg {
	page: number
	limit: number
	status: number // 状态 支付状态 0全部 1未支付 2已支付 3失败
	date_type: number // 时间范围 0 全部 1 当天 2 最近7天 3 最近60天
}

export interface GetUserPayListInfo extends ErrMsg {
	ctime: string // 时间
	ctype: number // 充值类型, SysPayType, 1 VIP充值 2 线上充值 3银行卡充值 4赠送 5小额支付  6 专享支付
	pay_name: string //
	point: number // 金额
	usdt_point: number // 货币类型为usdt时的usdt金额
	real_point: number // 实际金额
	status: number // 状态 支付状态 1未支付 2已支付 3失败
	order_no: string // 交易番号
	time_unix: number
	cost_point: number // 三分充值手续费
}

export interface GetUserPayListRsp extends ErrMsg {
	page: number
	limit: number
	total: number
	list: Array<GetUserPayListInfo>
}

export interface SetBankPwdReq extends ErrMsg {
	bank_name?: string
	old_pwd: string
	new_pwd: string
	set_type?: number
}

export interface ForgetBankPwdReq extends ErrMsg {
	phone: string
	acode: string
	code: string
	pwd: string
}

export interface LoginBankReq extends ErrMsg {
	pwd: string
}

export interface LoginBankRsp extends ErrMsg {
	bank_point: number
}

export interface DealBankPointReq extends ErrMsg {
	type: number // 1存 2取
	point: number
}

export interface DealBankPointRsp extends ErrMsg {
	bank_point: number
	point: number
}

export interface GetAllPayPutInfo extends ErrMsg {
	name: string
	point: number
	id: number
	type: number // 1充值 2提现
}

export interface GetAllPayPutListRsp extends ErrMsg {
	list: Array<GetAllPayPutInfo>
}

export interface UserNewDownPayReq extends ErrMsg {
	pay_key: string // 充值类型,参考constCom.NewPayType
	pay_type_id: string //
	price: number // 金额,单位:元,可带两位小数
	attach: string // 附加参数
	device: UserPayDevices // 版本信息
	activity_id: number // 参加的活动id, 参考constCom.LimitTimeFirstPayActivity
	activity_param: string // 参加的活动附加参数
	app_sdk_data?: string // 上报信息
}

export interface UserNewDownPayRsp extends ErrMsg {
	url: string // 充值链接
	qr_code: string // 充值二维码字符串
	type: string
	order_id: number
	order_no: string
	ret: number // 1返回数据
}

export interface GetUserDownPayDataReq extends ErrMsg {
	order_id: number
}

export interface UserDownPayRsp extends ErrMsg {
	url: string
	type: string
	order_id: number
	order_no: string
	pay_sdk_type: number
	token?: string
	le_pay_url?: string
	attach_param: string // 附加参数 json字符串格式
	ret: number // 1返回数据
	tServer: any // 支付盾
	qr_code: string // 支付二维码
}

export interface ExternalGameReq extends ErrMsg {
	gid: number // 游戏ID
}

export interface ExternalGameRsp extends ErrMsg {
	url: string
	locks?: Array<LockT>
}

export interface RewardPackInfo extends ErrMsg {
	uid: number // 玩家
	nick_name: string // 玩家昵称
	platid: number // 平台ID
	app_id: number // app_id
	his_pay: number // 历史充值
	his_win: number // 历史盈亏
	pack_point: number // 红包金额
	pack_type: number // 红包类型
	order_no: string // ID
	ctime: string // 创建时间
	ptime: string // 领取时间
	puid: number // 管理员
	pname: string // 管理员账号名称
	desc: string // 描述
}

export interface RewardPackRsp extends ErrMsg {
	status: boolean
	msg: string
}

export interface GetRewardPackCountRsp extends ErrMsg {
	total: number
	list: Array<RewardPackCountInfo>
}

export interface RewardPackCountInfo extends ErrMsg {
	id: string // 红包ID
	point: number // 红包金额
	pack_type: number // 红包类型
	orderNo: string
	desc: string
}

export interface ReceiveRewardPackReq extends ErrMsg {
	id: string
}

export interface SendManualRedpackEvent extends ErrMsg {
	platid: number // 平台ID
	app_id: number // app_id
	uid: number // 玩家
	pack_point: number // 红包金额
	pack_type: number // 红包类型
	desc: string // 描述
}

export interface MyRewardsRsp extends ErrMsg {
	data: Array<Rewards>
}

export interface Rewards extends ErrMsg {
	id: string // id 领取时用到
	bill_type: number // 账变类型（更详细）
	reward_type: number // 奖励类型 // 配置类型; 1.Vip奖励配置, 2.活动奖励配置, 3.任务奖励配置, ....
	title: { [key: string]: string } // 标题
	desc: { [key: string]: string } // 描述
	img: string // 图片
	itime: number // 派发时间
	end_itime: number // 截至领取时间 -1 永久
	props: Array<PromoItemCfg> // 道具
	point: number // 固定金额
	vip_int: number // vip积分
	task_int: number // 任务积分
}

export interface ReceiveRewardsReq extends ErrMsg {
	id: string // id
}

export interface ReceiveRewardsRsp extends ErrMsg {
	point: number // 固定金额
	pay_pro: number // 充值比例 n/万
	flow_pro: number // 流水比例比例 n/万
	vip_int: number // vip积分
	task_int: number // 任务积分
	props: Array<PromoItemCfg> // 道具
}

export interface MyRewardHistoryReq extends ErrMsg {
	page: number
	limit: number
	day_type: number // 时间 1 今天 2 最近7天 3 最近60天
	reward_type: number // 奖励类型
	bill_type: number // 账变类型（更详细）
}

export interface MyRewardHistoryRsp extends ErrMsg {
	data: Array<RewardHistory>
}

export interface RewardHistory extends ErrMsg {
	bill_type: number // 账变类型（更详细）
	reward_type: number // 奖励类型
	title: { [key: string]: string } // 标题
	point: number // 固定金额
	vip_int: number // vip积分
	task_int: number // 任务积分
	props: Array<PromoItemCfg> // 道具
	itime: number // 领取时间
}

export interface RewardCfg extends ErrMsg {
	reward_type: number // 配置类型; 1.Vip奖励配置, 2.活动奖励配置, 3.任务奖励配置, ....
	title: { [key: string]: string } // 标题
	desc: { [key: string]: string } // 描述
	img: string // 图片
	point: number // 固定金额
	vip_int: number // vip积分
	task_int: number // 任务积分
	props: Array<PromoItemCfg> // 道具 id,多个逗号分隔
	valid_time: number // 有效时间,单位秒; 0.没有时间限制
}
